### ISSUE TITLE
TGMPA calls WordPress functions before they are available

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-plugin-boilerplate#136]
Documenting this issue which has previously been logged in #12 and #115.

This fails when `gulp phpdoc_doc` is run.

I had an elaborate workaround in place, but as TGMPA is now also potentially clashing with PHPCS, this needs revisiting.

## WordPress dependencies

`did_action()` is one of several WordPress helpers used by TGMPA.

### `did_action()`

>  Fatal error: Call to undefined function did_action() in /Volumes/DanBackup/Websites/wpdtrt-plugin-boilerplate/vendor/tgmpa/tgm-plugin-activation/class-tgm-plugin  
  -activation.php on line XXXX

`did_action()` is defined in `./wp-includes/plugin.php`. It is used to prevent setup scripts from running more than once.

```
// class-tgm-plugin-activation.php

class TGM_Plugin_Activation {
  ...

  if ( did_action( 'plugins_loaded' ) ) {
    load_tgm_plugin_activation();
  } else {
    add_action( 'plugins_loaded', 'load_tgm_plugin_activation' );
  }
}
```

### `ABSPATH`

Assuming that the `did_action` error was fixed by using `function_exists()`, we would then see this error:

> Warning: require_once(ABSPATHwp-admin/includes/class-wp-list-table.php): failed to open stream: No such file or directory in /Volumes/DanBackup/Websites/wpdtrt-plugin-boilerplate/vendor/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php on line XXXX

`ABSPATH` is defined in `./wp-load.php`. It is used to determine the path to core WordPress files.

```
if ( ! class_exists( 'WP_List_Table' ) ) {
  require_once ABSPATH . 'wp-admin/includes/class-wp-list-table.php';
}

if ( ! class_exists( 'TGMPA_List_Table' ) ) {
    class TGMPA_List_Table extends WP_List_Table {
        ...
    }
}
```

## Timing & execution

A WordPress environment is created to run the WPUnit tests. WordPress functions aren't available before this.

`ABSPATH` is used in `require` statements, which fire as soon as `class-tgm-plugin-activation.php` is itself required.

This is problematic because something (e.g. the autoloader, or PHPDocumentor) appears to include this file *before* the WordPress environment is available.

### Relevance to PHPDocumentor

TGMPA supplements WordPress by adding support for the loading of unpublished plugins. WordPress is only available within the WPUnit environment (i.e. when tests are running) so is not included by the Composer package and cannot be documented by PHPDocumentor. Therefore TGMPA does not need to be documented either.

The goal is simply to prevent TGMPA from interfering with PHPDocumentor which is used to document other the core plugin and it's direct dependencies.

### TGMPA Autoloader

The steps prior to this error are:

> Writing lock file
> Generating autoload files

Each package defines the files that should be autoloaded. This makes any classes in these files available, without having to explicitly `require` the file.

```
// tgmpa/tgm-plugin-activation/composer.json

{
  ...
  "autoload": {
    "files": ["class-tgm-plugin-activation.php"]
  }
  ...
}
```

But the TGMPA example also tells users to explicitly `require` this file:

```
// tgmpa/tgm-plugin-activation/example.php

require_once dirname( __FILE__ ) . '/class-tgm-plugin-activation.php';

add_action( 'tgmpa_register', 'my_theme_register_required_plugins' );
```

So I do the same:

```
// Plugin.php

class Plugin {
    protected function wp_setup() {
        ...
        add_action( 'tgmpa_register', array( $this, 'wp_register_plugin_dependencies' ) );
        ...
    }

    public function wp_register_plugin_dependencies() {

        require_once $this->get_path() . 'vendor/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php';
        ...
}
```

Regardless, it is the autoloader which creates the issues here. Given that code is also loaded manually, is the autoloader actually required?

### The autoload files

`class-tgm-plugin-activation.php` is loaded as follows:

```
// autoload_files.php

...
return array(
    ...
    'a5f882d89ab791a139cd2d37e50cdd80' => $vendorDir . '/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php',
    ...
}
```

```
// autoload_static.php

...
    public static $files = array (
        ...
        'a5f882d89ab791a139cd2d37e50cdd80' => __DIR__ . '/..' . '/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php',
        ...
    }
...
```

Commenting these lines out allows `gulp phpdoc_doc` to run as normal.

## Solutions

Updating TGMPA to the latest `dev-master` version did not help.

### Option 1 - Tweak the PHPDocumentor config

`./phpdoc.dist.xml` specifies which files should and shouldn't be documented.

```
gulp.task("phpdoc_doc", function () {
        ...

        .pipe(shell([
            "vendor/bin/phpdoc --config phpdoc.dist.xml"
        ]));
});
```

Changing the `parser` and `transformer` (output) targets does change the output folder, but changing the `file` and `directory` (input) sources, to target a folder containing no PHP, does nothing to solve the TGMPA error.

### Option 2 - Remove the autoload from TGMPA

1. Edit `tgmpa/tgm-plugin-activation/composer.json` to remove `autoload` object
2. Also remove the `autoload` object from `composer/installed.json` (https://stackoverflow.com/a/43528570)
3. `composer dump-autoload`
4. `autoload_files.php` and `autoload_static.php` are both updated to exclude TGMPA
5. `gulp phpdoc_doc` runs normally

This means that it should be possible to fork TGMPA and apply step (1) to the fork. 

### Option 3 - Exclude TGMPA from root autoload

```
// wpdtrt-plugin-boilerplate/composer.json

    "autoload": {
        "psr-4": {
            "DoTheRightThing\\WPDTRT_Plugin_Boilerplate\\r_1_4_23\\": "src"
        },
        "exclude-from-classmap": [
            "/vendor/tgmpa/*"
        ]
    },
```

1. Make the changes above (and also try with`/tgmpa/*` and `tgmpa/*`)
2. `composer dump-autoload`
3. This had no effect.

### Option 4 - Add a check for the WordPress environment

https://gist.github.com/RalfAlbert/1593410#file-_wp_environment_check-php-L101-L121

This could be incorporated into TGMPA, but it is doubtful whether the maintainers would want to add this, given that it is my particular Gulp build which is causing problems here.

**Comment by dotherightthing** [comment]
Resolved using Option 2

**Comment by lbngoc** [comment]
I see that TGMPA fixed this issue at here https://github.com/TGMPA/TGM-Plugin-Activation/pull/488 but it was still not released.
I use this command at this time to get current branch with this fix for my project `composer require  tgmpa/tgm-plugin-activation:dev-develop`
